사전 과제 제출
drum-grammer/docker-pro-2308 pull request #113
Opened 2023-07-27 07:03 UTC by mkwkw

2023-07-31 21:34 UTC, drum-grammer requested changes
사전 미션 확인했습니다. 👍
고생하셨습니다.

다만 수정사항 하나 남겼으니 확인 부탁드립니다.

그럼, 8/1 오늘 첫 수업 때 뵐게요. 🙏

2023-07-31 21:34 UTC, drum-grammer commented on mission/mkwkw/mission.md
> +이미지를 만들어서 컨테이너를 생성하거나, 관리하고, 컨테이너를 다시 이미지로 만들 수 있게 도와주는 오픈소스 플랫폼입니다.
네, 컨테이너화를 지원하는 중요한 소프트웨어 플랫폼으로 애플리케이션 개발과 배포를 간편하게 해줍니다.

`컨테이너를 다시 이미지로 만들 수 있게 도와주는` 라는 설명은 조금 수저이 필요할 것 같습니다.
도커로 실행 중인 컨테이너를 다시 이미지로 만드는 기능은 직접적으로 제공되는 것은 아닙니다.

2023-08-01 04:57 UTC, mkwkw commented
도커 설명 수정하였습니다!

2023-08-04 01:01 UTC, drum-grammer approved these changes
수정 사항 확인 했습니다. 고생하셨습니다.

2023-08-04 01:01 UTC, merged