사전미션 제출
drum-grammer/docker-pro-2308 pull request #15
Opened 2023-07-16 08:59 UTC by jjinwo0

2023-07-16 09:00 UTC, jjinwo0 commented
사전미션 제출 완료하였습니다.

2023-07-18 02:28 UTC, drum-grammer requested changes
사전 미션 확인 완료했습니다.
고생 많으셨습니다 :)

다만 몇가지 수정사항이 있는데, 확인해주세요. 🙏

8/1 첫 수업 때 뵈요. 🙏

2023-07-18 02:28 UTC, drum-grammer commented on mission/박진우/.obsidian/appearance.json
> +{
https://obsidian.md/ 좋은 툴을 쓰시는 군요 🤭
저도 처음 보는 건데 한번 써봐야겠네요 👍

2023-07-18 02:28 UTC, drum-grammer commented on mission/박진우/.obsidian/appearance.json
> +{
다만 .obsidian/ 하위의 설정 정보들은 제외하고 푸쉬해주세요. 🙏

2023-07-18 02:28 UTC, drum-grammer commented on mission/박진우/Docker 사전 미션.md
> +>Docker는 컨테이너 기반 가상화 플랫폼으로싸, 애플리케이션을 컨테이너화하고 이를 효율적으로 관리하는 도구입니다. Docker는 개발 환경을 일관되게 유지하고, 다양한 플랫폼과 환경에서의 배포를 단순화하며, 서비스의 확장성을 향상시킬 수 있는 많은 기능과 도구를 제공합니다.
플랫폼으로싸 -> 플랫폼으로써 오타가 있네요 ㅎㅎ 내용은 좋습니다. 🙏

2023-07-24 13:22 UTC, jjinwo0 commented on mission/박진우/.obsidian/appearance.json
> +{
사전에 확인하지 못했네요...🥺 조치하도록 하겠습니다...!
개인 일정으로 늦게 확인하여 죄송합니다 🥲

2023-07-24 13:23 UTC, jjinwo0 commented on mission/박진우/Docker 사전 미션.md
> +>Docker는 컨테이너 기반 가상화 플랫폼으로싸, 애플리케이션을 컨테이너화하고 이를 효율적으로 관리하는 도구입니다. Docker는 개발 환경을 일관되게 유지하고, 다양한 플랫폼과 환경에서의 배포를 단순화하며, 서비스의 확장성을 향상시킬 수 있는 많은 기능과 도구를 제공합니다.
아앗... 조금 부끄럽네요 ㅎㅎ...😅
좋게 봐주셔서 감사합니다!

2023-07-28 12:27 UTC, drum-grammer approved these changes
수정 사항 확인 했습니다. 상세히 작성해주셨네요.
그럼 8/1 첫수업 때 뵙겠습니다.

2023-07-28 12:27 UTC, drum-grammer commented on mission/박진우/Docker 사전 미션.md
> +> Docker는 컨테이너 기반 가상화 플랫폼으로써, 애플리케이션을 컨테이너화하고 이를 효율적으로 관리하는 도구입니다. Docker는 개발 환경을 일관되게 유지하고, 다양한 플랫폼과 환경에서의 배포를 단순화하며, 서비스의 확장성을 향상시킬 수 있는 많은 기능과 도구를 제공합니다.
👍

2023-07-28 12:28 UTC, merged