8월 사전과제 제출
drum-grammer/docker-pro-2308 pull request #166
Opened 2023-07-30 06:17 UTC by sangsang0114

2023-07-31 23:00 UTC, drum-grammer approved these changes
컨테이너화를 지원하는 중요한 소프트웨어 플랫폼으로
애플리케이션 개발과 배포를 간편하게 해줍니다.

2023-07-31 23:00 UTC, drum-grammer commented on mission/Yoon/mission.md
> +* 데이터 및 프로그램을 격리시키는 기능을 제공하는 소프트웨어
네, 컨테이너화를 지원하는 중요한 소프트웨어 플랫폼으로
애플리케이션 개발과 배포를 간편하게 해줍니다.

2023-07-31 23:04 UTC, drum-grammer requested changes
사전 미션 확인했습니다. 👍
고생하셨습니다.

코멘트 확인 부탁드립니다.

그럼, 8/1 오늘 첫 수업 때 뵐게요. 🙏

2023-07-31 23:04 UTC, drum-grammer commented on mission/Yoon/mission.md
> +* 원하는 개발환경을 코드로 구성하는 방법을 제공하는 것
위 내용 중 일부 `도커 파일은 원하는 개발환경을 코드로 구성하는 방법을 제공하는 것` 내용은
수정하면 더 좋은 설명이 될 것 같습니다.
 

도커 파일은 개발환경을 코드로 구성한다기 보다는
이미지를 생성하기 위한 빌드 스크립트입니다. 
도커 파일 안에는 이미지를 구성하는데 필요한 커맨드와 설정들이 기술되어 있으며, 
컨테이너를 실행하기 위한 환경 설정 정보를 포함합니다.

따라서 옳은 설명은 다음과 같습니다:

도커 파일은 도커 이미지를 생성하기 위한 빌드 스크립트로, 컨테이너를 실행하기 위한 환경 설정 정보를 포함합니다.

2023-08-01 09:45 UTC, sangsang0114 commented
바쁘셨을텐데 피드백 주셔서 감사합니다 :)
앞으로 2주간 잘 부탁드릴게요.

2023-08-04 20:41 UTC, drum-grammer requested changes
수정 사항 확인 했습니다. 다만 contest 폴더가 커밋에 포함 되었네요. 해당 내용 제외 부탁드립니다. 🙏

2023-08-07 10:45 UTC, sangsang0114 commented
git이 아직 익숙하지 않아서 콘테스트 참가하려고 했을 때 실수를 했었네요.
수정 완료했습니다! 번거롭게 해드려서 죄송해요

2023-08-07 13:15 UTC, drum-grammer approved these changes
사전 미션 확인했습니다. 👍
고생하셨습니다.
그럼, 8/8 화요일 세번째 수업 때 뵐게요. 🙏

2023-08-07 13:15 UTC, merged