사전 과제 제출합니다.
drum-grammer/docker-pro-2308 pull request #195
Opened 2023-07-31 16:38 UTC by yelm-212

![Uploading docker-hello-world.png…]()

2023-08-01 21:11 UTC, drum-grammer approved these changes
사전 미션 확인했습니다. 👍
고생하셨습니다.
그럼, 8/3 목요일 두번째 수업 때 뵐게요. 🙏

2023-08-01 21:11 UTC, drum-grammer requested changes
다만 루트폴더에 올리신 그림 파일은 본인 미션 파일로 옮겨주세요. 🙏

2023-08-02 00:30 UTC, yelm-212 commented
해당사항 반영해 수정하였습니다. 감사합니다!

2023-08-04 01:07 UTC, drum-grammer approved these changes
수정 사항 확인 했습니다. 고생하셨습니다.

2023-08-04 01:07 UTC, merged