사전 미션
drum-grammer/docker-pro-2308 pull request #27
Opened 2023-07-19 05:43 UTC by hhpp1205

2023-07-20 03:35 UTC, drum-grammer requested changes
사전 미션 확인 완료했습니다.
고생 많으셨습니다 :)

다만 mission/ 하위 폴더에 본인 폴더를 만드셔서, 신규 파일에 작업해주셔야 할 것 같습니다.

8/1 첫 수업 때 뵈요. 🙏

2023-07-20 05:47 UTC, hhpp1205 commented
수정했습니다

2023-07-28 12:29 UTC, drum-grammer approved these changes
수정사항 확인 했습니다. 고생하셨습니다. 👍

2023-07-28 12:29 UTC, drum-grammer commented on mission/홍성민/answer.md
> +격리된 공간에서 프로세스가 동작하는 기술로 기존 VM 과는 달리 별도의 운영체제를 요구하거나 포함하지 않아 더 가볍다.
👍

2023-07-28 12:30 UTC, merged