Ranunclulus mission 다시 제출합니다!
drum-grammer/docker-pro-2308 pull request #71
Opened 2023-07-25 00:20 UTC by ranunclulus

사전 미션 제출합니다

2023-07-28 09:27 UTC, drum-grammer requested changes
사전 미션 확인 완료했습니다.
고생 많으셨습니다 :)

일부 누락된 미션이 있어, 확인 하시고 추가바랍니다.

8/1 첫 수업 때 뵈요. 🙏

2023-07-28 09:27 UTC, drum-grammer commented on mission/ranunclulus/mission.md
> +Container는 다양한 컴퓨팅 환경에 쉽게 배포할 수 있도록 코드, 라이브러리 구성 파일과 같은 애플리케이션 구성을 압축한 가볍고 실행 가능한 소프트웨어 단위이자 프로세스이다. 즉 우리가 만드는 서비스를 Instructure as Code에 기반하여 컨테이너화하는 기술이다.
컨테이너 기술은 애플리케이션을 실행하는 데 필요한 모든 소프트웨어와 라이브러리, 설정 등을 하나로 묶어 격리된 환경에서 실행하는 기술을 말합니다. 이러한 격리된 환경은 호스트 시스템의 운영체제를 공유하지만 독립적으로 실행되며, 다른 컨테이너나 호스트 시스템에 영향을 주거나 받지 않습니다.

컨테이너는 가상 머신(VM)과는 다른 접근 방식을 가지고 있습니다. VM은 하이퍼바이저를 사용하여 여러 개의 운영체제를 호스트 시스템 위에 가상으로 만들고, 각 운영체제마다 독립된 환경을 제공하는 방식이지만, 컨테이너는 도커(Docker)와 같은 컨테이너 기술을 사용하여 애플리케이션을 격리된 환경에서 실행합니다. 이로 인해 컨테이너는 가볍고 빠르며, 호스트 시스템에 영향을 덜 주면서 여러 애플리케이션을 동시에 실행할 수 있습니다.

컨테이너 기술은 개발자와 시스템 관리자들이 애플리케이션의 개발, 배포, 운영을 편리하게 관리할 수 있도록 도와주며, 클라우드 컴퓨팅과 마이크로서비스 아키텍처를 구현하는 데 매우 유용하게 사용됩니다.

2023-07-28 09:27 UTC, drum-grammer commented on mission/ranunclulus/mission.md
> +
2번과 3번 내용도 추가 부탁드립니다.

2023-07-29 04:49 UTC, ranunclulus commented on mission/ranunclulus/mission.md
> +
추가해 주신 답변 보고 VM이랑 Container의 차이점에 대해 알게 되었습니다! 감사합니다. :) 누락된 부분도 수정해서 Commit하였습니다!

2023-07-31 21:05 UTC, drum-grammer requested changes
코멘트를 확인하고 수정해주셨네요. 👍
도커의 장점을 설명해 주신 부분에 대해 간단히 코멘트 남겼으니 한번 더 확인 부탁드릴께요.

2023-07-31 21:05 UTC, drum-grammer commented on mission/ranunclulus/mission.md
> +컨테이너 기반의 애플리케이션을 개발하고 배포하고 실행할 수 있는 오픈 소스 플랫폼이다. 개인 컴퓨터의 infrastructure과 격리시켜 앱을 실행하기 때문에 소프트웨어 실행 속도가 빠르다는 장점을 가진다. infrastructure as code 개발 환경 셋팅을 코드로 진행하고, DevOps를 지향하여 코드를 쓰고 배포하기까지 시간 단축시킨다.
```
개인 컴퓨터의 infrastructure과 격리시켜 앱을 실행하기 때문에 소프트웨어 실행 속도가 빠르다
```
위 표현에 대해 조금은 수정이 필요할 것 같습니다.
개인 컴퓨터 자원 / 커널 위에서 바로 실행하는 것이 당연히 더 빠를 것입니다.

다만 가상화 기술 중 가상 머신 방식은 OS 까지 추상화하여 무거워 질 수 밖에 없는데,
컨테이너 방식은 불필요한 OS 가상화는 생략할 수 있기 때문에 상대적으로 빠른 것입니다.

위와 같은 이유로,
컨테이너 가상화 방식은 가상 머신 방식에 비해 가볍고 빠르게 실행되는 특성을 가지며, 
도커의 장점 중 하나는 이러한 경량성과 빠른 실행 속도입니다. 

따라서 "infrastructure와 격리 시켰기 때문에 실행 속도가 빨라진다"라는 표현은 정확하지 않습니다. 

`가상화를 가상 머신의 비해 가볍기 때문에 컨테이너 방식이 가상 머신 방식에 비해 빠르다`라고 설명할 수 있을 것 같네요. 👍

2023-08-04 01:06 UTC, drum-grammer approved these changes
수정 사항 확인 했습니다. 고생하셨습니다.

2023-08-04 01:06 UTC, merged