pre-mission
drum-grammer/docker-pro-2308 pull request #99
Opened 2023-07-26 17:22 UTC by truelightwater

사전 미션 수행입니다.

2023-07-28 13:04 UTC, drum-grammer requested changes
사전 미션 확인 완료했습니다.
고생 많으셨습니다 :)

오타 하나 커멘트 남겨두었는데 수정부탁드립니다.

8/1 첫 수업 때 뵈요. 🙏

2023-07-28 13:04 UTC, drum-grammer commented on mission/true/preMission.md
> +- 컨테이너 기술을 기반으로 한 일종의 가상화 플랫폼입니다. 가상화는 물리적인 하드웨어를 효율적으로 활용하기 위해서 하드웨어 공간 위에 가상의 머신을 만드는 것입니다.
👍

2023-07-28 13:04 UTC, drum-grammer commented on mission/true/preMission.md
> +- 토커를 이용하면 이미지를 실행시켜 컨테이너로 만들거나, 생성된 컨테이너를 관리하거나 컨테이너를 다시 이미지로 만드는 작업을 할 수 있습니다.
오타가 있는 것 같군요: 토커 -> 도커

2023-08-01 12:45 UTC, truelightwater reviewed
오타 수정했습니다.

2023-08-04 00:59 UTC, drum-grammer approved these changes
수정 확인했습니다. 고생 많으셨습니다.

2023-08-04 00:59 UTC, merged